// Pure helpers of the «Поддержать OMP» build scripts (gen-donate-qr.mjs, donate-code.mjs); tested in tests/scripts.
import { createPrivateKey, createPublicKey, sign } from 'node:crypto';
import QRCode from 'qrcode';

/** Modules of empty border around the code (the QR standard asks for 4). */
export const QUIET = 4;

/**
 * QR code of `url` as an SVG path in module units (quiet zone included): one «M x y h n v 1 h -n z» per run of dark
 * modules in a row. `bits`: the rows of the code without the quiet zone, «1» dark (the Android TV player draws it).
 */
export function qrData(url) {
  const qr = QRCode.create(url, { errorCorrectionLevel: 'M' });
  const n = qr.modules.size;
  const dark = (x, y) => !!qr.modules.get(y, x);
  let path = '';
  let bits = '';
  for (let y = 0; y < n; y++) {
    let x = 0;
    while (x < n) {
      if (!dark(x, y)) {
        x++;
        continue;
      }
      let run = 1;
      while (x + run < n && dark(x + run, y)) run++;
      path += 'M' + (x + QUIET) + ' ' + (y + QUIET) + 'h' + run + 'v1h-' + run + 'z';
      x += run;
    }
    for (let i = 0; i < n; i++) bits += dark(i, y) ? '1' : '0';
  }
  return { url, modules: n, size: n + 2 * QUIET, path, bits };
}

/** The committed module src/ui/donateQr.ts for `url`. */
export function qrModule(url) {
  const d = qrData(url);
  return (
    '// Generated by scripts/gen-donate-qr.mjs (npm run gen:donate-qr) from DONATE_URL of src/lib/donate.ts: do not edit.\n' +
    '// QR code of the donation link drawn by the TV player card; `size` includes the quiet zone, `bits` are the rows\n' +
    '// without it («1» dark) for the Android TV native player.\n' +
    'export const DONATE_QR = {\n' +
    '  url: ' + JSON.stringify(d.url) + ',\n' +
    '  size: ' + d.size + ',\n' +
    '  modules: ' + d.modules + ',\n' +
    '  path: ' + JSON.stringify(d.path) + ',\n' +
    '  bits: ' + JSON.stringify(d.bits) + ',\n' +
    '};\n'
  );
}

/** DONATE_URL of src/lib/donate.ts (the QR link), read from its source text. */
export function donateUrlFrom(source) {
  const m = /export const DONATE_URL = '([^']*)'/.exec(source);
  if (!m) throw new Error('DONATE_URL not found in src/lib/donate.ts');
  return m[1];
}

const MONTH_RE = /^(\d{4})-(0[1-9]|1[0-2])$/;

/** The support code of `month` («2026-11») signed with an Ed25519 private key (PEM). */
export function supportCode(month, privatePem) {
  if (!MONTH_RE.test(month)) throw new Error('Месяц в формате ГГГГ-ММ, например 2026-11');
  const key = createPrivateKey(privatePem);
  if (key.asymmetricKeyType !== 'ed25519') throw new Error('Нужен ключ Ed25519');
  const sig = sign(null, Buffer.from('omp-support:' + month, 'ascii'), key);
  return 'OMP-' + month + '-' + sig.toString('base64url');
}

/** The raw 32-byte public key (base64url) of an Ed25519 private key (PEM). */
export function publicKeyOf(privatePem) {
  const der = createPublicKey(createPrivateKey(privatePem)).export({ format: 'der', type: 'spki' });
  return Buffer.from(der.subarray(der.length - 32)).toString('base64url');
}
